package com.nick.entity;

import java.io.Serializable;
import java.util.Date;

public class SbMsgPushLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.push_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String pushId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.type
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.longitude
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.latitude
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.city
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.district
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.street
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.community
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String community;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.roadandlanes
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String roadandlanes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.house_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String houseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.building_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String buildingNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.unit
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.gate_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String gateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.village
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String village;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.org_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.fulladdr
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String fulladdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.lsdz_pdbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String lsdzPdbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.zaglssjwzrqdm
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String zaglssjwzrqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.shjz_pdbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String shjzPdbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.dzzczbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String dzzczbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.dzzzybs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String dzzzybs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.state
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.push_status
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String pushStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.push_desc
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String pushDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.building_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String buildingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.status
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.creator
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.create_time
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.update_user
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_msg_push_log.update_time
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sb_msg_push_log
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.push_id
     *
     * @return the value of sb_msg_push_log.push_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.push_id
     *
     * @param pushId the value for sb_msg_push_log.push_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setPushId(String pushId) {
        this.pushId = pushId == null ? null : pushId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.id
     *
     * @return the value of sb_msg_push_log.id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.id
     *
     * @param id the value for sb_msg_push_log.id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.type
     *
     * @return the value of sb_msg_push_log.type
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.type
     *
     * @param type the value for sb_msg_push_log.type
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.longitude
     *
     * @return the value of sb_msg_push_log.longitude
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.longitude
     *
     * @param longitude the value for sb_msg_push_log.longitude
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.latitude
     *
     * @return the value of sb_msg_push_log.latitude
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.latitude
     *
     * @param latitude the value for sb_msg_push_log.latitude
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.city
     *
     * @return the value of sb_msg_push_log.city
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.city
     *
     * @param city the value for sb_msg_push_log.city
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.district
     *
     * @return the value of sb_msg_push_log.district
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.district
     *
     * @param district the value for sb_msg_push_log.district
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.street
     *
     * @return the value of sb_msg_push_log.street
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.street
     *
     * @param street the value for sb_msg_push_log.street
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.community
     *
     * @return the value of sb_msg_push_log.community
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.community
     *
     * @param community the value for sb_msg_push_log.community
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.roadandlanes
     *
     * @return the value of sb_msg_push_log.roadandlanes
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getRoadandlanes() {
        return roadandlanes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.roadandlanes
     *
     * @param roadandlanes the value for sb_msg_push_log.roadandlanes
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setRoadandlanes(String roadandlanes) {
        this.roadandlanes = roadandlanes == null ? null : roadandlanes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.house_num
     *
     * @return the value of sb_msg_push_log.house_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getHouseNum() {
        return houseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.house_num
     *
     * @param houseNum the value for sb_msg_push_log.house_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setHouseNum(String houseNum) {
        this.houseNum = houseNum == null ? null : houseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.building_num
     *
     * @return the value of sb_msg_push_log.building_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getBuildingNum() {
        return buildingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.building_num
     *
     * @param buildingNum the value for sb_msg_push_log.building_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setBuildingNum(String buildingNum) {
        this.buildingNum = buildingNum == null ? null : buildingNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.unit
     *
     * @return the value of sb_msg_push_log.unit
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.unit
     *
     * @param unit the value for sb_msg_push_log.unit
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.gate_num
     *
     * @return the value of sb_msg_push_log.gate_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getGateNum() {
        return gateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.gate_num
     *
     * @param gateNum the value for sb_msg_push_log.gate_num
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setGateNum(String gateNum) {
        this.gateNum = gateNum == null ? null : gateNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.village
     *
     * @return the value of sb_msg_push_log.village
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.village
     *
     * @param village the value for sb_msg_push_log.village
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setVillage(String village) {
        this.village = village == null ? null : village.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.org_id
     *
     * @return the value of sb_msg_push_log.org_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.org_id
     *
     * @param orgId the value for sb_msg_push_log.org_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.fulladdr
     *
     * @return the value of sb_msg_push_log.fulladdr
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getFulladdr() {
        return fulladdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.fulladdr
     *
     * @param fulladdr the value for sb_msg_push_log.fulladdr
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setFulladdr(String fulladdr) {
        this.fulladdr = fulladdr == null ? null : fulladdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.lsdz_pdbs
     *
     * @return the value of sb_msg_push_log.lsdz_pdbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getLsdzPdbs() {
        return lsdzPdbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.lsdz_pdbs
     *
     * @param lsdzPdbs the value for sb_msg_push_log.lsdz_pdbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setLsdzPdbs(String lsdzPdbs) {
        this.lsdzPdbs = lsdzPdbs == null ? null : lsdzPdbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.zaglssjwzrqdm
     *
     * @return the value of sb_msg_push_log.zaglssjwzrqdm
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getZaglssjwzrqdm() {
        return zaglssjwzrqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.zaglssjwzrqdm
     *
     * @param zaglssjwzrqdm the value for sb_msg_push_log.zaglssjwzrqdm
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setZaglssjwzrqdm(String zaglssjwzrqdm) {
        this.zaglssjwzrqdm = zaglssjwzrqdm == null ? null : zaglssjwzrqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.shjz_pdbs
     *
     * @return the value of sb_msg_push_log.shjz_pdbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getShjzPdbs() {
        return shjzPdbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.shjz_pdbs
     *
     * @param shjzPdbs the value for sb_msg_push_log.shjz_pdbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setShjzPdbs(String shjzPdbs) {
        this.shjzPdbs = shjzPdbs == null ? null : shjzPdbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.dzzczbs
     *
     * @return the value of sb_msg_push_log.dzzczbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getDzzczbs() {
        return dzzczbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.dzzczbs
     *
     * @param dzzczbs the value for sb_msg_push_log.dzzczbs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setDzzczbs(String dzzczbs) {
        this.dzzczbs = dzzczbs == null ? null : dzzczbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.dzzzybs
     *
     * @return the value of sb_msg_push_log.dzzzybs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getDzzzybs() {
        return dzzzybs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.dzzzybs
     *
     * @param dzzzybs the value for sb_msg_push_log.dzzzybs
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setDzzzybs(String dzzzybs) {
        this.dzzzybs = dzzzybs == null ? null : dzzzybs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.state
     *
     * @return the value of sb_msg_push_log.state
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.state
     *
     * @param state the value for sb_msg_push_log.state
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.push_status
     *
     * @return the value of sb_msg_push_log.push_status
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.push_status
     *
     * @param pushStatus the value for sb_msg_push_log.push_status
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setPushStatus(String pushStatus) {
        this.pushStatus = pushStatus == null ? null : pushStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.push_desc
     *
     * @return the value of sb_msg_push_log.push_desc
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getPushDesc() {
        return pushDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.push_desc
     *
     * @param pushDesc the value for sb_msg_push_log.push_desc
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setPushDesc(String pushDesc) {
        this.pushDesc = pushDesc == null ? null : pushDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.building_id
     *
     * @return the value of sb_msg_push_log.building_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.building_id
     *
     * @param buildingId the value for sb_msg_push_log.building_id
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId == null ? null : buildingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.status
     *
     * @return the value of sb_msg_push_log.status
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.status
     *
     * @param status the value for sb_msg_push_log.status
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.creator
     *
     * @return the value of sb_msg_push_log.creator
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.creator
     *
     * @param creator the value for sb_msg_push_log.creator
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.create_time
     *
     * @return the value of sb_msg_push_log.create_time
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.create_time
     *
     * @param createTime the value for sb_msg_push_log.create_time
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.update_user
     *
     * @return the value of sb_msg_push_log.update_user
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.update_user
     *
     * @param updateUser the value for sb_msg_push_log.update_user
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_msg_push_log.update_time
     *
     * @return the value of sb_msg_push_log.update_time
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_msg_push_log.update_time
     *
     * @param updateTime the value for sb_msg_push_log.update_time
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}