package com.nick.dao;

import com.nick.entity.SbMsgPushFail;

public interface SbMsgPushFailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sb_msg_push_fail
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    int deleteByPrimaryKey(String pushId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sb_msg_push_fail
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    int insert(SbMsgPushFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sb_msg_push_fail
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    int insertSelective(SbMsgPushFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sb_msg_push_fail
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    SbMsgPushFail selectByPrimaryKey(String pushId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sb_msg_push_fail
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    int updateByPrimaryKeySelective(SbMsgPushFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sb_msg_push_fail
     *
     * @mbg.generated Tue Dec 17 16:23:13 CST 2019
     */
    int updateByPrimaryKey(SbMsgPushFail record);
}